#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtsass
Version  : 0.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/a8/ed/f5a384bce45c7cdde521c939a7d655da736d6dace99a3c8366a5404abf69/qtsass-0.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a8/ed/f5a384bce45c7cdde521c939a7d655da736d6dace99a3c8366a5404abf69/qtsass-0.3.0.tar.gz
Summary  : Compile SCSS files to valid Qt stylesheets.
Group    : Development/Tools
License  : MIT
Requires: qtsass-bin = %{version}-%{release}
Requires: qtsass-python = %{version}-%{release}
Requires: qtsass-python3 = %{version}-%{release}
Requires: libsass
BuildRequires : buildreq-distutils3
BuildRequires : libsass

%description
# QtSASS: Compile SCSS files to Qt stylesheets
[![License - MIT](https://img.shields.io/github/license/spyder-ide/qtsass.svg)](./LICENSE.txt)
[![OpenCollective Backers](https://opencollective.com/spyder/backers/badge.svg?color=blue)](#backers)
[![Join the chat at https://gitter.im/spyder-ide/public](https://badges.gitter.im/spyder-ide/spyder.svg)](https://gitter.im/spyder-ide/public)<br>
[![Github build status](https://github.com/spyder-ide/qtsass/workflows/Tests/badge.svg)](https://github.com/spyder-ide/qtsass/actions)
[![Codecov coverage](https://img.shields.io/codecov/c/github/spyder-ide/qtsass/master.svg)](https://codecov.io/gh/spyder-ide/qtsass)
[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/spyder-ide/qtsass/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/spyder-ide/qtsass/?branch=master)

%package bin
Summary: bin components for the qtsass package.
Group: Binaries

%description bin
bin components for the qtsass package.


%package python
Summary: python components for the qtsass package.
Group: Default
Requires: qtsass-python3 = %{version}-%{release}

%description python
python components for the qtsass package.


%package python3
Summary: python3 components for the qtsass package.
Group: Default
Requires: python3-core
Provides: pypi(qtsass)
Requires: pypi(libsass)

%description python3
python3 components for the qtsass package.


%prep
%setup -q -n qtsass-0.3.0
cd %{_builddir}/qtsass-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596131619
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qtsass

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
